# Generated by Django 2.0.2 on 2018-02-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
    ]
