# Generated by Django 2.0.2 on 2018-02-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
    ]
