# Generated by Django 2.0.2 on 2018-03-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fechaCreacion',
            new_name='Fecha de creacion',
        ),
    ]
