# Generated by Django 2.0.2 on 2018-03-02 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180301_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Fecha de creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
    ]
